### ISSUE TITLE
Minor missing word in Section 3.4.5

### ISSUE THREAD

**Issue by KnightAdz** [topepo/FES#12]
In the version dated "2018-05-12", there is a word missing in Section 3.4.5, 3rd paragraph:

> and that the true value represented by the green vertical line.
> and that the true value *is* represented by the green vertical line.

**Comment by KnightAdz** [comment]
Also a missing letter in the description of figure 3.11

>Averaging the individual reample performance values reduces the variation in the profile.
>Averaging the individual resample performance values reduces the variation in the profile.


(Is it ok to post further section 3 typos in this thread or would you prefer me to open a new issue?)

**Comment by topepo** [comment]
As long as they are in the same, chapter appending to an open issue is fine. Thanks
