### ISSUE TITLE
Typos in `1 Introduction`

### ISSUE THREAD

**Issue by jwillage** [topepo/FES#13]
In the version dated "2018-05-12", several typos in the `Introduction` section. 

####  1.2.7 Big Data ####
>First, it simple might not

Should be "simply" not "simple"

>For high bias, lo variance models

Should be "low" not "lo"

>doubling or tripling the amount of training data is unlikely to more the parameter estimates

Incomplete sentence, should read something about "unlikely to **improve** the parameter estimates", etc.

####  1.4 Feature Selection ####  
>with 0 possible values, is converted to a set of -1 binary variables

Should read "a set of 0-1 binary variables".

**Comment by topepo** [comment]
That was leftover text from a different example. Thanks for catching that. The changes will be in the new released version
