### ISSUE TITLE
Please cite relevant prior work

### ISSUE THREAD

**Issue by JohnMount** [topepo/FES#14]
I honestly think encoding categoricals chapter should cite our prior work on effects/impact coding and vtreat.  It is provably stronger than hashing (we have a note on that if you want) and our work has citation instructions here github.com/WinVector/vtre…

**Comment by topepo** [comment]
`"citation instructions here github.com/WinVector/vtre…"` got cut off in your message. 

Are you saying that we should discuss those specific method or that we have discussed things that you have done work on and want citations added to our current materials?
