### ISSUE TITLE
A few minor issues picked up

### ISSUE THREAD

**Issue by StefanZaaiman** [topepo/FES#16]
In the version dated "2018-05-12", the following minor issues were picked up: 

**Section 1.2.2 Supervised and Unsupervised Procedures:**
Exploratory data analysis (EDA) (Tukey 1977) is used understand the 
Should be (seems like a “to” is missing there):
Exploratory data analysis (EDA) (Tukey 1977) is used **_to_** understand the

**Section 1.2.4 The Model versus the Modeling Process**
Summary measures for each model, such as model accuracy, are used to understand the level of difficulty for the problem **_and and_** to determine which models appear to best suit the data
Should be (the one “and” must be deleted):
Summary measures for each model, such as model accuracy, are used to understand the level of difficulty for the problem **_and_** to determine which models appear to best suit the data

**Section 1.2.5 Model Bias and Variance**
Linear regression is linear in the model parameters and adding polynomial terms to the model can be effective way
Should be (“an” is missing):
Linear regression is linear in the model parameters and adding polynomial terms to the model can be **_an_** effective way

**Section 1.2.5 Model Bias and Variance**
was improved by modifying the predictor variables and was able to show results on par with a support vector machine model (low bias)
Shouldn’t this be (the example mentioned compared to a neural network model, not an SVM model?):
was improved by modifying the predictor variables and was able to show results on par with a **_neural network model_** (low bias)

**Comment by topepo** [comment]
Thanks. The changes will be in the new released version
