### ISSUE TITLE
Figure 2.3 has the wrong pairs highlighted

### ISSUE THREAD

**Issue by eddelbuettel** [topepo/FES#18]
In the currently visible version, Figure 2.3 highlights the wrong pairs of variables. 

Three blocks are highlighted, and the text below the figures describes which.  However, what is in the figure does not correspond.  I include an elarged screenshot to make it more obvious:

![image](https://user-images.githubusercontent.com/673121/40237252-7fd43166-5a75-11e8-9b41-295ce56d003e.png)

We have 'adjacent pairs' 1, 2 and 8 highlighted. I think we want 3, 9 and 10 instead.

**Comment by topepo** [comment]
Fixed in sources. Thanks.
