### ISSUE TITLE
Qualitative x quantitative in 6.2.2

### ISSUE THREAD

**Issue by nazareno** [topepo/FES#2]
There is a _qualitative_ mistakenly used instead of _quantitative_ in Section 6.2.2 that may cause confusion. The first paragraph says

> Binning, also known as categorization or discretization, is the process of translating **a qualitative variable** into a set of two or more qualitative buckets. For example, a variable might be translated into quantiles

I believe it was meant to say a **quantitative** variable. 

Btw, if this is still debatable, I'd argue that _categorical_ would be clearer than _qualitative_ for describing variables that cannot be ordered throughout the book.

**Comment by topepo** [comment]
You are correct. I've changed it to

> Binning, also known as categorization or discretization, is the process of translating a quantitative variable into a set of two or more qualitative buckets (i.e., categories).

I don't think that I want to convert all references to qualitative to categorical though.

**Comment by topepo** [comment]
Fixed in the sources. Thanks
