### ISSUE TITLE
Wrong bibtex name expansion 

### ISSUE THREAD

**Issue by eddelbuettel** [topepo/FES#20]
In _Section 3.6 Model Optimization and Tuning_ the sentence

> See I, Bengio, and Courville (2016) for an excellent primer on neural networks and deep learning  
models.

has just 'I.' for Ian Goodfellow.   

Maybe you have Lastname, Firstname wrong ...  I generally stick to _First Last and Anotherfirst Anotherlast and Yetmorefirst Yetmorelast_ in my bibtex file.

**Comment by topepo** [comment]
Fixed. Thanks
