### ISSUE TITLE
Suggestions for section on "Creating Features from Text Data"

### ISSUE THREAD

**Issue by juliasilge** [topepo/FES#24]
The following feedback is based on the version dated "2018-05-24" and is for section 5.5: **Creating Features from Text Data**.

### Typos

> The rate of hyperlinks in the STEM profiles was 0.21% while 11.6% of the non-STEM profiles contained at least one link.

The rate for the STEM profiles is 21.0%.

> Therefore the words or phrases used in these open text fields could be very important to predictng the outcome.

### List of common methods for preprocessing text data

I would suggest adding even more basic processing here, such as tokenization (single word, n-grams), cleaning such as removing HTML (sometimes it is informative, like with the links), etc. You don't need to mention everything here, but [here are typical types of super basic features for text](https://github.com/mkearney/textfeatures).

### Discussion of stemming

Stemming *can* be useful but it is not always. For example, check out [*Comparing Apples to Apple* by Schofield and Mimno](https://transacl.org/ojs/index.php/tacl/article/view/868). Often practitioners assume stemming is good practice but detailed study has found that, for topic modeling at least, stemming doesn't help and it sometimes hurts. I have found similar results with text classification. It's at the very least something that practitioners should not automatically use. Instead, build a model with stemming and without and compare, for example, AUC. I don't know that you will want to spend the pages here on training both and comparing, but I would definitely mention that it is not necessarily going to make the model better to stem and include the Schofield Mimno reference. Here is [some more recent work by the same authors](http://www.cs.cornell.edu/~xanda/winlp2017.pdf) about the effect of text preprocessing on models for text:

> We find that many  common  practices  either  have  no measurable effect or have a negative effect after accounting for biases induced by feature selection.

😬😬😬

### Discussion of tf-idf

For the paragraphs on tf-idf, I'd suggest the following minor edits:

> The strategy shown here for computing and evaluating features from text is fairly simplistic and is not the only approach that could be taken. One other method for determining relevant features uses the term frequency-inverse document frequency (`tf-idf`) statistic (Amati and Van Rijsbergen 2002). Here the goal is to find words or terms that are important to individual documents in the collection of documents at hand. For example, if the words in this book were processed, there are some that would have high frequency (e.g. predictor, encode, or resample) but are unusual in most other contexts.

> For a word `W` in document `D`, the term frequency `tf` is the number of times that `W` is contained in `D` (usually adjusted for the length of `D`). The inverse document frequency `idf` is a weight that will normalize by how often the word occurs in the current collection of documents. As an example, suppose the term frequency of the word `feynman` in a specific profile was 2. In the sample of profiles used to derive the features, this word occurs 55 times out of 10,000. The inverse document frequency is usually represented as the log of the ratio, or `log2(10000/55)`
or 7.5. The `tf-idf` value for feynman in this profile would be `2×log2(10000/55)` or 15. However, suppose that in the same profile, the word `internet` also occurs twice. This word is more prevalent across profiles and is contained at least once 1529 times. The `tf-idf` value here is 5.4; in this way the same raw count is down-weighted according to its abundance in the overall data set. The word `feynman` occurs the same number of times as `internet` in this hypothetical profile, but `feynman` is more distinctive or important (as measured by `tf-idf`) because it is more rare overall, and thus possibly more effective as a feature for prediction.

**Comment by topepo** [comment]
`textfeatures` is a huge help. Any idea what `n_tobe` computes? The docs don't really say. At some point, I'd like to develop a bunch of text-oriented recipe steps. 

Thanks for the edits, you are a much better writer than I. 

On stemming and stop words: those articles are very convincing. I did the keyword selection without any word editing and came up with virtually the same results (`nurs` was dropped and another was picked up). I'll remove the extra processing and describe those steps closer to the end. 

I'm also going to split out the types of features; the keyword effect is large (as expected):

![image](https://user-images.githubusercontent.com/5731043/44859653-93113e80-ac42-11e8-847a-40452671bc12.png)

**Comment by juliasilge** [comment]
`textfeatures` is really great but the documentation leaves a lot to be desired currently. Mike does have the repo marked "experimental" still? FWIW `n_tobe` [measures "to be" verbs.](https://github.com/mkearney/textfeatures/blob/1cc49e1440df7744f3d2794a3c720bd03b0d4ba6/R/count.R#L179)

I would love for him to get this package matured because I would like to feel better about recommending it to folks.

**Comment by topepo** [comment]
Thanks for all of your help.
