### ISSUE TITLE
typo in chapter 6.3.1.2

### ISSUE THREAD

**Issue by uwesterr** [topepo/FES#28]
in version date "2018-05-12" in chapter 6.3.1.2

> The second **row** from the left in Figure 6.9 

should be 
> The second **column** from the left in Figure 6.9   

hm, since this is the second occurrence of this issue maybe my english fails here. in that case sorry for the inconvenience.

if this is a mistake then this also occurring in chapter 6.3.1.3 
> The ICA components are shown in the third row of Figure 6.9

**Comment by topepo** [comment]
No, you were completely right about these. Thanks!
