### ISSUE TITLE
Typos - Pedram

### ISSUE THREAD

**Issue by PedramNavid** [topepo/FES#3]
from preface: believe effectively should be effective here.

> In addition to having a good approach to the modeling process, building an **effectively** predictive model requires other good practices.

**Comment by PedramNavid** [comment]
Max, not sure what kind of reviews you're seeking since copy-editing hasn't been completed yet, but also found this phrase a little clunky and hard to understand..

> "the expert guided, relevant predictors that we collected are not in a form which models can adequately uncover the essential predictive information for the response"

**Comment by topepo** [comment]
How does this sound instead:

> Despite our attempts to follow these good practices, we are sometimes frustrated to find that the best models have less-than-anticipated, below useful predictive performance.  This lack of performance may be due to a simple to _explain, but difficult to pinpoint, cause:  relevant predictors that were collected are represented in a way that models have trouble using them to achieve good performance._

**Comment by PedramNavid** [comment]
I'd take out the them (I hope I'm not being pedantic).

> This lack of performance may be due to a simple to explain, but difficult to pinpoint, cause: _relevant predictors that were collected are represented in a way that models have trouble using to achieve good performance._

**Comment by PedramNavid** [comment]
Hi Max, let me know if you think I should open up a new issue for each typo/sentence issue, but that might get excessive. Here's another:

From 1.1 introduction, a simple example:

> A more complex model would do a better job at capturing the data patterns but would be much **more less** interpretable.

Believe you just meant less.

**Comment by topepo** [comment]
Thanks. I suggest making a different issue per chapter.

**Comment by topepo** [comment]
These are fixed in the sources. Thanks.
