### ISSUE TITLE
Typo in Section 5.5

### ISSUE THREAD

**Issue by AndrewKostandy** [topepo/FES#34]
In the version dated "2018-05-12", Section 5.5, the number 0.21 is stated as a percentage in the first line below but used as a proportion a few lines later also shown below. Table 5.2 also confirms that the number should be 0.21 (or 21%).
```
> The rate of hyperlinks in the STEM profiles was 0.21% while 11.6% of the non-STEM profiles contained at least one link.

> For the STEM profiles, the odds of containing a hyperlink are relatively small with a value of 0.21 / 0.79 = 0.266.
```

**Comment by topepo** [comment]
Got it. thanks!
