### ISSUE TITLE
minor typos section 3

### ISSUE THREAD

**Issue by stecaron** [topepo/FES#37]
Great material, thanks for sharing that !

In the version dated "2018-05-12", there is a minor typo in section 3.6 where there should be a dot after the reference.

```
> algorithms that can be employed (Chong and Żak 2008) These methods
> algorithms that can be employed (Chong and Żak 2008). These methods
```

Also, in section 3.7, you enumerated 2 things : 

```
1. It prevents the test set from being used during the model development process and
2. Many evaluations of an external data set are used to assess the differences.
```

I know it's a quite minor detail, but the "end" between the bullet points might be inconsistent with the rest of the book enumerations. I don't think there is a strict rule for that, but regarding those things I often opt for consistency. You seem to frequently use upper-case at the beginning and ending with a dot. That being said, it's not a big deal anyways.

I really look forward to read the missing values handling section (one important concern for practitioners handling real-world data). Please give some love to this section.

Thanks

**Comment by topepo** [comment]
Thanks!
