### ISSUE TITLE
I want to translate this project into Chinese.

### ISSUE THREAD

**Issue by LG-1** [topepo/FES#39]
Dear Max Kuhn and Kjell Johnson,
I think this project is a great work and will help a lot people know how to deal problems in FE.

also, i didn't see knowledge system introduced the FE should how to push.Before this.

this project can teach me know how, why and next. thats why I think this is a great job.

so, I want to translate this project into Chinese to help more people know it.

I don't know if this is OK?Max Kuhn and Kjell Johnson can give me some feedbacks, if anything is wrong.https://www.ourantech.club/2018/06/21/feature-engineering/

**Comment by FontTian** [comment]
good job.
