### ISSUE TITLE
Some ideas for interactions chapter

### ISSUE THREAD

**Issue by LluisRamon** [topepo/FES#40]
In Chapter 7 Detecting Interaction Effects and particularly in Section 7.4.2 The Lasso, I think that it could be interesting to provide some comments on 
> Michael Lim & Trevor Hastie 2016 Learning interactions via hierarchical group-lasso regularization 

The authors provide a package with their method in CRAN called [glinternet](https://cran.r-project.org/web/packages/glinternet/index.html).

It was compared in

> A systematic comparison of statistical methods to detect interactions in exposome-health associations. https://www.ncbi.nlm.nih.gov/pubmed/28709428

and glinternet was one of the methods with better performance.

**Comment by pejovic** [comment]
Dear Max and Kjell

In relation to your book, we have recently published the paper "Sparse regression interaction models for spatial prediction of soil properties in 3D", which you could find interesting and useful. It can be related to the Chapter 7 "Detecting interaction effects", especially with the sub-Chapter 7.4.2. "lasso". In our paper, we demonstrated use of lasso and hierarchical lasso for detecting important interactions for spatial prediction of soil variables at different soil depths. One of the conclusions was that 3D prediction
of soil properties using linear models benefits from interaction effects among spatial predictors and soil depth only if detection of important interactions is done via lasso. Modeling and evaluating procedures are given in the paper and the approach is demonstrated on three case studies and compared to other linear modeling approaches (OLS and stepwise regression). We'll be glad if you find our paper
useful.

Link to the paper:
https://www.sciencedirect.com/science/article/pii/S009830041730852X

**Comment by topepo** [comment]
@LluisRamon 

> In Chapter 7 Detecting Interaction Effects and particularly in Section 7.4.2 The Lasso, I think that it could be interesting to provide some comments on 
> > Michael Lim & Trevor Hastie 2016 Learning interactions via hierarchical group-lasso regularization 
>
>The authors provide a package with their method in CRAN called [glinternet](https://cran.r-project.org/web/packages/glinternet/index.html).

It is a really interesting paper that I was eager to test out. Unfortunately, the user interface to that R package is so bad, I feel that it would be irresponsible to use it. Those are strong words, but I don't think that the average R user would be able to successfully navigate their data input requirements or the format of their output. It is very frustrating.

**Comment by LluisRamon** [comment]
Thanks for considering, it was a suggestion and your concerns are pretty reasonable.
