### ISSUE TITLE
Section 5.1 Creating Dummy Variables

### ISSUE THREAD

**Issue by r0f1** [topepo/FES#43]
In this section it is explained that when encoding weekday, a categorical variable with 7 manifestations, it is okay to use only 6 dummy variables. Or generally speaking, when encoding a variable with N manifestations, it is okay to use only N-1 dummy variables

I agree that this is the right approach for linear models. For tree models however, I would be cautious about this approach. I would advise everybody to use all N dummy variables (not just N-1) for tree models. If you use a, say, Decision Tree, and you have no dummy variable for category N (assuming that this is the reference category that was left out), and the Decision Tree should learn some property about category N, it would have to split up every other category (1..N-1) until it eventually can learn the property about category N.

This should be mentioned in this section or somewhere in the chapter.

**Comment by topepo** [comment]
Done. thanks
