### ISSUE TITLE
Section 3.2.1 Minor Typo

### ISSUE THREAD

**Issue by danielwo** [topepo/FES#45]
Section 3.2.1
2018-09-09
"performace" should be "performance".  "that what it would" should be "than what it would"

>In general, this type of sample makes the model performace metric appear worse that what it would be without the sample.

**Comment by danielwo** [comment]
A couple of lines down "acutal" should be "actual"
>However, it is more often the case that we are interested in predicting the acutal response value rather than just the rank

**Comment by topepo** [comment]
Thanks
