### ISSUE TITLE
Wrong color reference to figure 1.2b

### ISSUE THREAD

**Issue by feinmann** [topepo/FES#5]
In the version dated "2018-05-12", the diagonal line in figure 1.2b in section 1.1 is refered to as being red, while it is dashed grey (is there a typo in 'a' ineffective model rather being 'an' ineffictive model? No native here :)):

> [...] upper left corner while a ineffective model will stay along the diagonal line shown in red. [...]

**Comment by topepo** [comment]
Thanks. The changes will be in the new released version
