### ISSUE TITLE
Clarification on 4.2.5 Correlation Matrix Plots

### ISSUE THREAD

**Issue by mpettis** [topepo/FES#51]
Section: 4.2.5 Correlation Matrix Plots
Date: 2018-09-08

Could you give a little more clarification on what the heatmap is showing?  You state that it is:

> 14-day lag in ridership across stations for non-holiday, weekdays in 2016 for the Chicago data.

However, as I read it, I'm not sure how that would work with what you are highlighting about the chart.  I tend to interpret the chart as the correlations in ridership (non-holiday, weekdays, 2016) between stations, with each x- and y- axis entry being a station, but non-lagged.  It doesn't make sense to lag them and then correlate them, as the correlation of lag-14 predictors against lag-14 predictors should be the same as correlations of the non-lagged predictors.

I may be misunderstanding what is going on, but to that end, it may be helpful to clarify.

Thanks for the book.

**Comment by topepo** [comment]
You are mostly right about the correlations being equal. However, the lagged data have a different number of rows than the original (and is in-line with the training set). 

The main reason that we used those is that they are the actual predictors that will be used.

**Comment by mpettis** [comment]
Thank you, that does make sense.

What I am angling for is, though, is for a definitive description of the plot, because I made guesses.  I'll be more explicit in what I am guessing at here, which I think might make things clearer in the text:

- The levels of the x and y axis are stations
- The color of the heat map represents, say, the correlation of the station on the x axis with the one on the y axis.  But the y-axis station ridership series value is 14-day lagged from the x-axis station ridership series value.
- The marginal tree hierarchy relationships group both the x-axis stations together in the same way that they do the y-axis stations because either a.) The hierarchy is based on the same metrics for both axis, or b.) grouping lag-14 by lag-14 values, which does reduce the series length, results in the same hierarchical clustering.
- This would also imply that the heat maps are slightly asymmetric, as

    cor(station A, lag_14(station B))

could be different from

    cor(lag_14(station A), station B)

Again, just a suggestion on where some additional information on what's going on in the plot may make things clearer.

Thanks,
Matt

**Comment by topepo** [comment]
The correlations shown are between `cor(lag_14(station A), lag_14(station B))`. For example, the point in the upper left corner is the correlation between the lag-14 data for UIC-Halsted and O'Hare:

![image](https://user-images.githubusercontent.com/5731043/53136146-f45bff80-354b-11e9-976a-a49ab1fcade5.png)

Assuming I've answered the question, your point about needing more clarification is good. I'll add some verbiage about this (unless you object to the explanation above).

**Comment by mpettis** [comment]
Hi Max,

The explanation works for me, and I think would be helpful to others.

Thank you,
Matt
