### ISSUE TITLE
Version: 2018-09-08 Section: 4.3.1 : Possible typos or errors

### ISSUE THREAD

**Issue by mpettis** [topepo/FES#52]
Version: 2018-09-08
Section: 4.3.1 Visualizing Relationships between Outcomes and Predictors

1. Very minor typo, missing posessive apostrophe on `profiles`, and I think I did it right, but should be checked.  I believe this:

> As an example, total length of all the profiles essays will be used to illustrate a possible solution.

should be this

> As an example, total length of all the profiles' essays will be used to illustrate a possible solution.

2. Wrong value quoted in text?

>  The maximum length was approximately 0K characters although 10% of the profiles contained less than 14 characters.

The charts make me think it should be at least 100, possibly 1K, based on next issue.

3. Wrong value referenced?

> Prior to a length of  10^3.5, the profile is slightly less likely than chance to be STEM. 

From the plot it is referring to, I'm reading that statement to refer to the point where the black line in 4.15(b) crosses the horizontal red baseline value.  According to that chart, that occurs at 10^1.5, not 10^3.5.  Otherwise, 10^3.5 is not show on the chart, and I assume was an extrapolation.

**Comment by topepo** [comment]
I had previously gotten two of these but missed the last one. Thanks. 

We might publish a new (final-ish) version Friday so let us know if you find anything else.
