### ISSUE TITLE
Question: level of feedback detail desired?

### ISSUE THREAD

**Issue by treysp** [topepo/FES#55]
I'm very much enjoying the book - thanks so much for writing it! 

Regarding feedback about the writing/language, are you interested in very detailed feedback that may involve stylistic choices?

Please find three examples below. I assume you'd be interested in the first but am less sure about the second and third.

--------------

Book version: 2019-02-22

1. Location: Preface, first reference. Typo: there is an extra "p" in the reference title word "Progression".
> Raimondi, C. 2010. “How I Won the Predict HIV Pprogression Data Mining Competition.”

2. Location: 1 Introduction, first paragraph below Figure 1.1. The phrase "locations for properties" might be more easily understood if worded "locations \_of\_ properties."
> "Figure 1.1 shows locations for properties in and around Ames Iowa, that were sold between 2006 and 2010."

3. Location: 1 Introduction, third paragraph. This might be simplified to "Parsimony also leads to a more interpretable model." Or "Parsimony also leads to more interpretable models."
> "Parsimony also leads to a higher capacity to interpret a model."

**Comment by topepo** [comment]
Anything that you want to give feedback on is great. Typos are the least critical since we will have the text copyedited soon. I'm most interested in references or methods that we should include (as well as mistakes).

**Comment by topepo** [comment]
Thanks!
