### ISSUE TITLE
Section 2.3 typos

### ISSUE THREAD

**Issue by lpatruno** [topepo/FES#61]
> The simple model, analogous to the statistical “null model” contains only an intercept term while the model complex model has a single term for an individual predictor from the risk set.

I'm guessing this should be

> The simple model, analogous to the statistical “null model” contains only an intercept term while the **more** complex model has a single term for an individual predictor from the risk set.

Date: 2019-02-22

Great book, btw.

**Comment by lpatruno** [comment]
And another

> At this point, one could move straight to tuning predictive models on the preprocessed and filtered the risk and/or the imaging predictors for the training set to see how well the predictors together identify stroke outcome. 

Not sure if the **and filtered the risk and/or** part should be there.

**Comment by kjell-stattenacity** [comment]
Thanks.  Fixedx
