### ISSUE TITLE
Section 2.4 typos

### ISSUE THREAD

**Issue by lpatruno** [topepo/FES#62]
Date: 2019-02-22

> The optimal subset size is determined using these results and the final RFE execution is one the entire training set and stops at the optimal size.

I believe **is one** is a typo.

> Since this is not a large set, an interaction model with potentially all 28 pairwise interactions.

This is not a sentence.

> The risk set, when only main effects are considered, the full set of 8 predictors is favored. 

This is not a sentence.

**Comment by kjell-stattenacity** [comment]
Corrected.
