### ISSUE TITLE
Section 3.2 Feedback

### ISSUE THREAD

**Issue by lpatruno** [topepo/FES#64]
Date: 2019-02-22

>It is possible, and not unusual, that a model could produce predicted values that have a strong linear relationship with the observed values but the predicted values do not conform to the 45 degree line of agreement.

This sentence is a bit hard to understand at first. Readers may not know what the **45 degree line of agreement** is. This reference seems to come out of nowhere. 

> The blue line is the linear regression fit between the observed and predicted values, while the black line represents the line of agreement.

What do you mean by **the line of agreement**? (Edit) After thinking about this, I realized it was another reference to the 45 degree line of agreement. The fact that this took some time to sink in may be a useful data point though.

> In this instance, we more profiles would be called STEM. 

I think **we more** should be **more**.

**Comment by topepo** [comment]
Thanks!
