### ISSUE TITLE
Typo in the preface references

### ISSUE THREAD

**Issue by cdr6934** [topepo/FES#66]
In the version dated "2019-02-22", on the Preface page, the following reference has a typo (Pprogression should be progression ) in the first reference of the section. 

> Raimondi, C. 2010. “How I Won the Predict HIV **Pprogression** Data Mining Competition.” http://blog.kaggle.com/2010/08/09/how-i-won-the-hiv-progression-prediction-data-mining-competition/.

**Comment by topepo** [comment]
Thanks
