### ISSUE TITLE
Missing words

### ISSUE THREAD

**Issue by feinmann** [topepo/FES#7]
Two small `fill-words` missing:

In the version dated "2018-05-12", at the end of paragraph 1.2.1:

> [...] The risk of this type of overfitting is especially dangerous when the number of data points is small and the number `of` potential predictors is very large. [...]

In the version dated "2018-05-12", at the beginning of paragraph 1.2.2:

> [...] Exploratory data analysis (EDA) (Tukey 1977) is used `to` understand the major characteristics of the predictors and outcome so that any particular challenges associated with the data can be discovered prior to modeling. [...]

**Comment by topepo** [comment]
Thanks. The changes will be in the new released version
