### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by jrfiedler** [topepo/FES#72]
I checked all of these in the book just now (2019-02-22 version), but I didn't check to see if they had been posted elsewhere.

1.2.5
  - insert "they" before "cannot" in "without modification, cannot describe"
  - drop the "a" in "Linear regression is a linear"
  - insert "an" before "effective" in "can be effective way of allowing"

1.2.6
  - remove first "the" from "without the knowing the"

1.2.7
  - "predictors data" should be "predictor data" ?

1.4
  - remove "to compensate" in "sequentially to compensate to improve" ?
  - insert "in the" before "course" in "occurs naturally course of"
  - remove "a" in "such a predictors"
  - change "models" to "model" (and probably hyphenate "low-bias") in "a low bias models"

2.3
  - remove first "model" in "the model complex model"
  - remove "the" in "and filtered the risk"
  - remove "there are", or maybe replace "can" with "to" in "there are more exploratory steps can"
  - maybe replace "pair-wise" with "pairwise" ?
  - maybe change "Clicking on" to something like "Hovering over" in "Clicking on a point will show the interaction term" ?

2.4
  - 1st paragraph: In the list of predictor sets, it's not clear to me what "and risk" means in "and risk, imaging predictors"
  - change "one" to "on" in "the final RFE procedure is one the entire training set" ?
  - 1st sentence after "The RFE procedure was applied to" is incomplete
  - maybe insert "with" at beginning of "The risk set, when only main effects are considered" ?
  - remove comma in "model has, at most 18 predictors" ?

3.1
  - change "these" to "this" or drop "set" from "these data set"

3.2.2
  - remove "we" from "we more profiles"

3.3
  - change "sets" to "set" or "set's" in "test sets results" ?

3.4
  - mismatch between text and Figure 3.5; the text says "three resamples", but the figure shows $B$ resamples

4.2.2
  - insert "in" before "several" in "will be illustrated several of the following sections"

4.2.3
  - change "a" to "an" in "as a input to models"

4.2.7
  - change "techniques" to "technique" in "We will delve into this techniques"

4.3.1
  - add a period after "string" in "a single text string The distribution of"
  - change "and" to "an" in "Larger profiles show and increase"

4.3.2
  - maybe change "statistics" to "statistic" in "more than half of the $\chi^2$ statistics"
  - maybe insert "often" after "drugs" in "using alcohol very often and drugs have an association"
  - maybe change "statistics" to "statistic" in "another third of the $\chi^2$ statistics"

chapter 5 intro
  - insert "of" after "series" in "a series `if/then` statements"

5.1
  - insert "the" before "estimate" in "In this case, estimate indicates"

5.2
  - insert "to" after "idea" in "a good idea understand why"

5.4
  - change "sets" to "set" in "a different data sets"
  - change "indicators" to "indicator" in "indicators variables"
  - insert "of" before "embedding" in "using a set _embedding features_ ?

5.6
  - remove "to" from "the profile to contains"
  - change "form" to "from" in "derived form"

5.7
  - remove one period from "tune the model.."

chapter 6 intro
  - 1st paragraph: drop last "e" on "develope"
  - 2nd-to-last paragraph, 1st sentence
    - add space in "organizedinto"
    - remove space before end-of-sentence period

6.1
  - something wrong with "be a a common scale"
    - just drop one of the "a"s?
    - change first "a" to "on"?

6.2
  - change "or" to "of" in "rich class or models"
  - something wrong with "the largest $R^2$ value seen in 1000 data sets was 18.3% although most data are less than 20%"
    - if the largest is 18.3, then *all* of the data are less than 20
    - should 20 be 10? Or 2? Some other number?
  - remove the first period from "inside of the resampling. process."

6.3.1
  - 1st paragraph: insert "to" in "related the response"
  - insert "of" in "a set artificial features"
  - figure 6.15 caption: change "and" to "an" in "fitting and autoencoder"
  - change "and" to "an" in "Figure 6.17(a) shows and example"

7.3
  - change "alternatively" to "alternative" in "An alternatively methodology"
  - change "approaches" to "approach" in "this interaction detection approaches"
  - duplicated "type" in "type of garage type"
  - something is missing in "the full model the individual predictors"; maybe insert "with" or "containing" or etc.

7.4
  - change comma to period in "interactions, Using"
  - change "statistics" to "statistic" in "a new statistics"
  - something is missing before "worse" in "The optimal single tree model worse"
  - remove apostrophe in "ensemble of trees' are"
  - remove one "that are" from "that are that are"

7.4.3
  - In the fourth paragraph, there's a mismatch in subscripts: "three predictors ($x_1$, $x_5, and $x_9$) ... two predictors, say, $x_3$ and $x_9$ ..."
  - remove first "s" from "interactions terms"

10.4
  - remove one "that" from "What we mean is that that"
  - first reference: change "Eata" to "Data"

10.5
  - drop "s" from "for each predictors"

11.2
  - remove one "are" from "are provided below are are organized" and change the other two to "is"; also this sentence seems like two sentences stuck together; maybe change to something like "is provided below, and is organized ..."
  - remove "of" or "coming from" from "p-value, of coming from this distribution"
  - remove "to" from "when to using p-values"
  - change "sub-filed" to "subfield"

11.3
   - change "creating" to "created" in "the models creating using all predictors"
   - change reference to Figure 11.5 in "The results are shown in the right-hand panel of Figure 11.6"
   - change "be" to "by" in "be removing irrelevant predictors"

11.4
  - change "original" to "originally" in first sentence

11.5
  - change "criteria" to "criterion" in "a criteria"

12.1
  - add apostrophe to "Bayes" in "Bayes formula" ? also, capitalize "formula" ?
  - change second "trend" to "tend" in "a slight trend where the non-STEM profiles trend to use less" ?

12.2
  - change "it" to "its" in "in it search"
  - remove "this" from "this the acceptance probability"
  - change "and" to "an" in "provides and additional layer"
  - change "solutions" to "solution" in "so the solutions is accepted"

12.2.1
  - insert period in "more appropriate An"
  - change "larger" to "large" in "is larger enough"

12.2.2
  - the book says "the iteration with the best area under the ROC curve (0.822) was 430" but there were a "maximum 326" iterations; eyeballing it from Figure 12.5, the max iteration looks like ~260
  - mismatch in number of predictors: "In the end, 54 predictors" (and the following table lists 54), vs "investigate if the 52 selected features"

12.2.5
  - change "On" to "One" in "On additional aspect"

12.3
  - insert "to" in "enables GAs harness"
  - remove "a" or "s" in "in a GAs"
  - change "features" to "feature" in "features subsets"
  - remove first "is" from "is to select parents is to"
  - remove one "performance" from "performance performance"

12.3.2
  - remove first "a" from "a having a sparse solution"
  - there seems to be a word missing in "models whose is to optimize"
  - change "numof" to "number of"
  - change "on" to "of" in "strengthen the influence on the desirability function"
  - remove one "of" from "the number of of predictors"

12.4
  - change "build" to "built" in the first sentence

12.5
  - change "optimization" to "optimize" in "did not optimization"

**Comment by topepo** [comment]
Thanks. The copy editor missed more than half of these.

**Comment by topepo** [comment]
I think that we got them all

**Comment by brshallo** [comment]
@topepo I think you missed:

> 11.3

> * change reference to Figure 11.5 in "The results are shown in the right-hand panel of Figure 11.6"
