### ISSUE TITLE
References, fill in authors

### ISSUE THREAD

**Issue by harrismcgehee** [topepo/FES#75]
## References

In the version dated "2019-06-21", I didn't know if you meant to leave a reference to authors blank.

> ———. 1994b. “Statistics Notes: Diagnostic tests 2: Predictive values.” British Medical Journal 309 (6947): 102.

Could become: 
`Altman, DG, and JM Bland. 1994b. “Statistics Notes: Diagnostic tests 2: Predictive values.” British Medical Journal 309 (6947): 102.`
Source: https://www.ncbi.nlm.nih.gov/pubmed/8038641

**Comment by topepo** [comment]
If you are seeing this in the References chapter, it does this when the authors are the same for multiple references:

![image](https://user-images.githubusercontent.com/5731043/60041496-93733e00-9689-11e9-80a9-cf3155e88aa9.png)

**Comment by harrismcgehee** [comment]
Thanks for your very nice reply to an uninformed correction!

**Comment by topepo** [comment]
No problem at all! There might be an option to change that bibtex behavior. I'll look into it.
