### ISSUE TITLE
Typo in caption of Figure 4.1

### ISSUE THREAD

**Issue by revodavid** [topepo/FES#76]
The caption currently reads: "Figure 4.1: Chicago Transit Authority ‘L’ map. For this illustration, we are **interesting** in predicting the ridership at the Clark/Lake station in the Chicago Loop. (Source: Wikimedia Commons, Creative Commons license)".

The word "interesting" should be "interested".

**Comment by kjell-stattenacity** [comment]
Fixed.  Thanks!
