### ISSUE TITLE
Suggestion for Encoding Categoricals

### ISSUE THREAD

**Issue by AllardJM** [topepo/FES#8]
Consider adding methods for encoding categorical variables that include entity embeddings or so called *-2vec where instead of using large sparse dummy variables or even hashing, we instead use dense embeddings. 

This is largely applicable when using a neural network but has been used more generally (GBDT). This method has successfully been used for winning kaggle contests. Most info in contained in blog posts, Jeremy howard's fastai course but there is this paper I am aware of:

Guo, C., & Berkhahn, F. (2016). Entity embeddings of categorical variables. arXiv preprint arXiv:1604.06737.

-----

Also, another useful technique - also popularized by Kaggle competitors is the mean-encoding (aka target encoding, aka likelihood encoding) approach. There are many variants but here are a couple descriptions:

https://www.coursera.org/learn/competitive-data-science/lecture/b5Gxv/concept-of-mean-encoding

http://www.statsblogs.com/2017/09/25/custom-level-coding-in-vtreat/

https://datascience.stackexchange.com/questions/11024/encoding-categorical-variables-using-likelihood-estimation

**Comment by topepo** [comment]
It would make sense to add a subsection on _supervised encodings_ in that chapter.

**Comment by topepo** [comment]
@alexpghayes When I do this for the town variable in the OkC data mentioned in Chapter 5 (`glm` = "fixed" and Bayesian `glm` as "pooled"), the log-odds estimates are pretty similar. However, the overall sample size isn't small so it would not shrink as much as smaller data sets 

![towns](https://user-images.githubusercontent.com/5731043/40079848-2a4fc14e-5857-11e8-99c6-9a6396d5c763.jpeg)

**Comment by AllardJM** [comment]
@topepo , 

Using a multi-level model can make a large difference when the cardinality is large and the data sparse, in my experience. Think about something like zipcodes and the use of logistic regression versus lmer(outcome~1 + (1|zipcode),data=DAT,family=binomial)
to estimate the encodings.

I like the idea of a supervised encoding section. It would be use mentioning transfer learning as well - since this is the starting point for most these days (e.g. NLP)

**Comment by dmi3kno** [comment]
I second the target encoding request. Additional useful references can be found in:
https://arxiv.org/abs/1611.09477

Supervised encoding extends beyond categorical features and one can think of, for example "y-aware dimensionality reduction methods" as a wider definition which would also capture "y-aware PCA"
http://www.win-vector.com/blog/2016/05/pcr_part2_yaware/

**Comment by alexpghayes** [comment]
@topepo Interesting. I'm planning to play around with this some in the next couple of days, I'll let you know if I find a compelling example where pooling makes a big difference.

**Comment by alexpghayes** [comment]
Looks like partial pooling for the encoding can have an impact:

![llh_encoding_comparisons](https://user-images.githubusercontent.com/15078251/40272114-1204cf18-5b5d-11e8-85a3-bec0ca5e85de.png)

Code (rough, will improve): https://gist.github.com/alexpghayes/d1ffb5c78b2e063d29b415a1a6bcb44e

**Comment by topepo** [comment]
A first pass at some code for recipes is the [`embed` package](https://github.com/topepo/embed) that uses `stan` or `tensorflow`. More documentation is [here](https://topepo.github.io/embed/). Feedback is welcome.
